### ISSUE TITLE
Can it be really usable now?

### ISSUE THREAD

**Issue by xeoshow** [FlexoVM/flexovm#3]
Just would like to know if it works with libgdx now?

**Comment by ashleyj** [comment]
It will work, but there would have to be some modifications to the libgdx code to reflect the package name change from org.robovm -> org.flexovm

There was talk about implementing a transformation layer to flexovm, so it'd "just work", but there's been no work on that so far.

**Comment by ashleyj** [comment]
There are some missing bindings, but it should work

**Comment by xeoshow** [comment]
Any official testing done? 
Really a pity after the struggling to get the code, and seems just on pending status? ...

**Comment by CaptainFuture** [comment]
Hi xeoshow. Do you want to join development and and get write access to add what you have in mind?!

**Comment by senagbe** [comment]
Hi, I'm interested to join and maybe have my employees commit code. My id is @senagbe. Most specifically, I am interested in adding static library support. No idea where to start but willing to put time, myself and my developers on this depending on how much it would take.

**Comment by Dexdev08** [comment]
Hey! Kind of a noob here but had java experience. How do we kickstart this
whole thing?

**Comment by Zubnix** [comment]
Hi, 

I have some Java and C experience and I would really like this project to succeed.

What I think is needed now:

expand the readme:
How to get a build working.
What is supported 
What is not supported (and never will be)
What should be supported (wanted).

Next an irc & ML for quick collaboration. Starting from there, development tasks & scope can be further defined.

Btw, there some quite a few forks out there but ideally only one should be used for community effort. I assume this one is the most popular?

**Comment by Dexdev08** [comment]
This is so far the fork ive seen.
I may have time off from work next week.

Anything i can do as a first step?like a concrete one?
Try building and log errors?

**Comment by Zubnix** [comment]
There's also: 
- https://github.com/bugvm/bugvm This one seems to be targeting mac users & ios it seems
- https://github.com/ashleyj/aura This one seems to be targeting desktop/non android/non ios users (<- my use case)

**Comment by Zubnix** [comment]
I've added #4 as a follow up
